### ISSUE TITLE
Add to NPM?

### ISSUE THREAD

**Issue by mattalco** [nleclerc/cordova-plugin-ios-disableshaketoedit#2]
Since Cordova 6.0.0 was released, they no longer support the Cordova Plugin Registry. Can you add this to NPM?

https://cordova.apache.org/news/2016/01/28/tools-release.html

**Comment by nleclerc** [comment]
yeah, i'll do it when i got a minute :-)

**Comment by mattalco** [comment]
Thank you :)

**Comment by nleclerc** [comment]
Done.
Package name is [cordova-plugin-ios-disableshaketoedit](https://www.npmjs.com/package/cordova-plugin-ios-disableshaketoedit).
